---
abstract: 'Perl extension for interfacing with my5C (3C/5C/HiC Data analysis).'
author:
  - 'Bryan R. Lajoie <bryan.lajoie@umassmed.edu>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cworld-crane_nature2015
requires:
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
